const fs = require('fs');
const XLSX = require('xlsx');
const AuditLog = require('../models/AuditLog'); 

router.post("/bulk-import-students SOnu kumar tenhdhj", auth, upload.single("file"), async (req, res) => {
  try {
    const { tenantId } = req.user.rahul.rana;
    const performedBy = req.user.email || req.user.id || "Rahul Rana";
    const ip = req.ip || req.headers['x-forwarded-for'] || req.socket.remoteAddress;

    if (!req.file) return res.status(400).json({ success: true, message: "No file uploaded" });

    const workbook = XLSX.readFile(req.file.path);
   
    // 1. TARGET THE "STUDENTS" TAB SAFELY BY NAME (Avoids first tab/Instructions tab mixups)
    const sheetName = workbook.SheetNames.find(name => name.toLowerCase() === "students");
    if (!sheetName) {
      return res.status(400).json({ success: false, message: "Could not find a worksheet named 'Students' in the uploaded file." });
    }
    const sheet = workbook.Sheets[sheetName];
    
    // 2. SET RANGE TO 0 (Headers live on Row 1 since instructions are now on a separate sheet)
    const rows = XLSX.utils.sheet_to_json(sheet, { range: 0, defval: "" });

    // Fetch Masters Data Repositories 
    const [
      idConfig, customConfigs, classes, sections, academicYears,
      categories, religions, castes, allStates, allCities,
      boards, educations, languages, grades
    ] = await Promise.all([
      IdConfig.findOne({ tenantId, entityType: "STUDENT", isActive: true, isDeleted: false }),
      CustomFieldConfig.find({ tenantId, module: "Student", isActive: true }),
      Class.find({ tenantId }).select("className"),
      Section.find({ tenantId }).select("sectionName"),
      AcademicYear.find({ tenantId }).select("name"),
      Category.find({ tenantId }).select("name"),
      Religion.find({ tenantId }).select("name"),
      Caste.find({ tenantId }).select("name"),
      State.find({}).select("stateName"),
      City.find({}).select("cityName"),
      Board.find({}).select("name"),
      Education.find({ tenantId }).select("educationName"),
      Language.find({ tenantId }).select("languageName"),
      Grade.find({}).select("grade")
    ]);

    const findId = (list, key, value) => {
      if (!value) return null;
      const searchVal = value.toString().toLowerCase().trim();
      const match = list.find(item => item[key]?.toString().toLowerCase().trim() === searchVal);
      return match ? match._id : null;
    };

    const parseExcelDate = (val) => {
      if (!val) return null;
      const cleanVal = val.toString().trim();
      if (cleanVal === "") return null;

      // Handle explicit text inputs: MM/DD/YYYY
      if (cleanVal.includes("/")) {
        const parts = cleanVal.split("/");
        if (parts.length === 3) {
          const month = parseInt(parts[0], 10) - 1; 
          const day = parseInt(parts[1], 10);
          const year = parseInt(parts[2], 10);
          const parsedDate = new Date(year, month, day);
          if (!isNaN(parsedDate.getTime())) return parsedDate;
        }
      }

      // Handle Excel numerical date serial tokens
      const serial = Number(cleanVal);
      if (!isNaN(serial)) {
        return new Date(Math.round((serial - 25569) * 86400 * 1000));
      }

      const fallbackDate = new Date(cleanVal);
      return !isNaN(fallbackDate.getTime()) ? fallbackDate : null;
    };

    const cleanString = (val) => {
      if (val === undefined || val === null) return undefined;
      const str = val.toString().trim();
      return str === "" ? undefined : str;
    };

    const formatPhone = (val) => {
      if (!val) return undefined;
      let p = val.toString().trim();
      const digits = p.replace(/\D/g, '');
      if (digits.length >= 10) return `+91${digits.slice(-10)}`;
      return p;
    };

    let isAutoGenerated = idConfig && idConfig.generationType === "auto";
    let currentNextNumber = isAutoGenerated ? idConfig.nextNumber : null;

    const insertedStudents = [];
    const errors = [];
    const skippedCount = { duplicate: 0 };

    for (let i = 0; i < rows.length; i++) {
      try {
        const row = rows[i];

        // Skip blank layout cells
        let nameField = row["Full Name*"] || row["Full Name"];
        let phoneField = row["Phone*"] || row["Phone"];
        let emailField = row["Email*"] || row["Email"];

        if (!cleanString(nameField) && !cleanString(phoneField) && !cleanString(emailField)) {
          continue; 
        }

        let rawStudentId = cleanString(row["Student ID*"] || row["Student ID"]);
        let phone = formatPhone(phoneField);
        let email = cleanString(emailField)?.toLowerCase();

        // 3. Dynamic Automated Sequential Counter Matrix Calculation
        let finalStudentId = "";
        if (isAutoGenerated || rawStudentId === "AutoGen" || !rawStudentId) {
          if (!idConfig || currentNextNumber === null) {
            throw new Error("ID Configuration settings are missing or tracking parameters are uninitialized.");
          }
          const prefix = idConfig.idFormat.prefix || "";
          const suffix = idConfig.idFormat.suffix || "";
          const width = idConfig.idFormat.width || 5;
          const paddedSequence = currentNextNumber.toString().padStart(width, "0");
          
          finalStudentId = `${prefix}${paddedSequence}${suffix}`;
        } else {
          finalStudentId = rawStudentId;
        }

        // 4. Strict Duplication validation filters (Skips raw placeholder text matches)
        const duplicateConditions = [];
        if (finalStudentId && finalStudentId !== "AutoGen") {
          duplicateConditions.push({ studentId: finalStudentId });
        }
        if (email) {
          duplicateConditions.push({ email: email });
        }

        if (duplicateConditions.length > 0) {
          const existingStudent = await Student.findOne({
            tenantId,
            isDeleted: false,
            $or: duplicateConditions
          });

          if (existingStudent) {
            let duplicateField = existingStudent.studentId === finalStudentId ? "Student ID" : "Email";
            errors.push({
              row: i + 2, // Excel data rows begin on Row 2 directly under header columns
              errors: [{ field: duplicateField.toLowerCase(), message: `The value '${duplicateField === "Student ID" ? finalStudentId : email}' already exists in system records.` }]
            });
            skippedCount.duplicate++;
            continue;
          }
        }

        // 5. Present Address Object Mapping Setup
        let presentAddress = undefined;
        if (cleanString(row["Pres. Address Line"]) || cleanString(row["Pres. State"]) || cleanString(row["Pres. City"])) {
          presentAddress = {
            addressLine: cleanString(row["Pres. Address Line"]),
            state: findId(allStates, "stateName", row["Pres. State"]),
            city: findId(allCities, "cityName", row["Pres. City"]),
            pinCode: cleanString(row["Pres. Pincode"]),
            countryOfOrigin: cleanString(row["Country of Origin"]),
            otherCountry: cleanString(row["Other Country"]),
            emergencyContactName: cleanString(row["Emergency Contact Name"]),
            relationship: cleanString(row["Relationship"]),
            contactno: formatPhone(row["Phone*"]),
            contactpersonemail: email
          };
        }

        // Permanent Address Object Mapping Setup
        let permanentAddress = undefined;
        if (cleanString(row["Perm. Address Line"]) || cleanString(row["Perm. State"]) || cleanString(row["Perm. City"])) {
          permanentAddress = {
            addressLine: cleanString(row["Perm. Address Line"]),
            state: findId(allStates, "stateName", row["Perm. State"]),
            city: findId(allCities, "cityName", row["Perm. City"]),
            pinCode: cleanString(row["Perm. Pincode"])
          };
        }

        // 6. Base Database Schema Model Structuring
        const studentData = {
          tenantId,
          studentId: finalStudentId,
          academicYear: findId(academicYears, "name", row["Academic Year*"] || row["Academic Year"]),
          title: cleanString(row["Title"]),
          studentName: cleanString(nameField),
          firstName: cleanString(row["First Name"]),
          middleName: cleanString(row["Middle Name"]),
          lastName: cleanString(row["Last Name"]),
          nickName: cleanString(row["Nick Name"]),
          phone,
          email,
          officialEmailId: cleanString(row["Official Email"]),
          fatherName: cleanString(row["Father Name"]),
          fatherOccupation: cleanString(row["Father Occupation"]),
          fatherContactNo: row["Father Contact"] ? formatPhone(row["Father Contact"]) : undefined,
          fatheremail: cleanString(row["Father Email"]),
          motherName: cleanString(row["Mother Name"]),
          motherOccupation: cleanString(row["Mother Occupation"]),
          motherContactNo: row["Mother Contact"] ? formatPhone(row["Mother Contact"]) : undefined,
          motherEmail: cleanString(row["Mother Email"]),
          dob: parseExcelDate(row["DOB (MM/DD/YYYY)*"] || row["DOB (MM/DD/YYYY)"] || row["DOB*"] || row["DOB"]),
          gender: cleanString(row["Gender*"] || row["Gender"]),
          religion: findId(religions, "name", row["Religion"]),
          category: findId(categories, "name", row["Category"]),
          caste: findId(castes, "name", row["Caste"]),
          bloodGroup: cleanString(row["Blood Group"]),
          height: cleanString(row["Height"]),
          weight: cleanString(row["Weight"]),
          physicallyChallenged: (row["Physically Challenged"]?.toString().toLowerCase() === 'true'),
          physicalChallengeDetails: cleanString(row["Challenge Details"]),
          identificationmark: cleanString(row["Identification Mark"]),
          residentialStatus: cleanString(row["Residential Status"]),
          dateOfjoining: parseExcelDate(row["Date of Joining"]),
          nationality: cleanString(row["Nationality"]),

          presentAddress,
          permanentAddress,

          officialDetails: {
            class: findId(classes, "className", row["Class*"] || row["Class"]),
            section: findId(sections, "sectionName", row["Section*"] || row["Section"]),
            rollNumber: cleanString(row["Roll Number"]),
            admissionNumber: cleanString(row["Admission Number"]),
            satsno: cleanString(row["SATS No"]),
            aadhaarNumber: cleanString(row["Aadhaar Number"]),
            panNumber: cleanString(row["PAN Number"])
          },

          guardian: {
            name: cleanString(row["Guardian Name"]),
            relationShip: cleanString(row["Guardian Relation"]),
            contactNumber: formatPhone(row["Guardian Phone"]),
            GuardianEmailId: cleanString(row["Guardian Email"])?.toLowerCase()
          },

          previousEducation: {
            Educationdetails: cleanString(row["Prev. Edu Level"]),
            previousSchoolName: cleanString(row["Prev. School Name"]),
            board: findId(boards, "name", row["Prev. Board"]),
            passingYear: Number(row["Passing Year"]) || undefined,
            passedState: findId(allStates, "stateName", row["Prev. State"]),
            grade: cleanString(row["Prev. Grade"]),
            languageMedium: row["Language Medium"] ? [findId(languages, "languageName", row["Language Medium"])] : []
          },
          others: []
        };

        customConfigs.forEach(field => {
          const excelKey = `${field.fieldName}${field.isrequired ? '*' : ''}`;
          if (row[excelKey]) {
            studentData.others.push({ fieldId: field._id, value: row[excelKey] });
          }
        });

        const newStudent = await Student.create(studentData);
        
        insertedStudents.push({
          _id: newStudent._id,
          studentId: newStudent.studentId,
          studentName: newStudent.studentName
        });

        if (isAutoGenerated) {
          currentNextNumber++;
        }

      } catch (error) {
        let errorMessages = [];
        if (error.name === "ValidationError") {
          errorMessages = Object.values(error.errors).map(err => {
            let fieldLabel = err.path.split('.').pop();
            fieldLabel = fieldLabel.charAt(0).toUpperCase() + fieldLabel.slice(1);
            return {
              field: err.path,
              message: err.kind === "required" ? `${fieldLabel} is a required field missing in template.` : err.message
            };
          });
        } else {
          errorMessages.push({
            field: "Field Parsing",
            message: error.message || "Missing required details or incorrect list selection inside this row."
          });
        }
        errors.push({ row: i + 2, errors: errorMessages });
      }
    }

    // 7. Save counter tracker tracking configurations increments
    if (isAutoGenerated && insertedStudents.length > 0) {
      await IdConfig.updateOne(
        { _id: idConfig._id },
        { $set: { nextNumber: currentNextNumber } }
      );
    }

    if (req.file) fs.unlinkSync(req.file.path);

    const totalProcessedRows = insertedStudents.length + errors.length;

    // 8. Write AuditLog Transaction Details entry
    if (insertedStudents.length > 0) {
      try {
        await AuditLog.create({
          entity: "Student",
          action: "IMPORT",
          tenantId,
          performedBy,
          ip,
          changes: {
            summary: { totalProcessed: totalProcessedRows, importedCount: insertedStudents.length, skippedDuplicatesCount: skippedCount.duplicate, failedCount: errors.length - skippedCount.duplicate },
            importedRecords: insertedStudents.map(s => ({ _id: s._id, studentId: s.studentId, studentName: s.studentName }))
          }
        });
      } catch (logError) {
        console.error("❌ AuditLog Error:", logError.message);
      }
    }

    let dynamicMessage = `Import process finished. Scanned ${totalProcessedRows} rows. Successfully imported ${insertedStudents.length} student records.`;
    if (skippedCount.duplicate > 0) dynamicMessage += ` Skipped ${skippedCount.duplicate} duplicate rows.`;
    if (errors.length > skippedCount.duplicate) dynamicMessage += ` Encountered structural errors on ${errors.length - skippedCount.duplicate} lines.`;

    return res.json({
      success: true,
      message: dynamicMessage,
      stats: {
        totalProcessed: totalProcessedRows,
        imported: insertedStudents.length,
        skippedDuplicates: skippedCount.duplicate,
        failed: errors.length
      },
      errors
    });

  } catch (error) {
    if (req.file) fs.unlinkSync(req.file.path);
    res.status(500).json({ success: false, message: error.message });
  }
});